### ISSUE TITLE
state sync not working

### ISSUE THREAD

**Issue by hdmiimdh** [EmpowerPlastic/empowerchain#226]
State sync doesn't seem to work now, can you please review and fix if possible.

empowerd version # 0.0.1

RPC node configuration
snapshot-interval = 2000
snapshot-keep-recent = 2

pruning = "custom"
pruning-keep-recent = "100"
pruning-keep-every = "2000"
pruning-interval = "10"

RPC link
SNAP_RPC="https://empower-testnet.nodejumper.io:443"

Error 
3:12PM ERR snapshot manager not configured
3:12PM ERR State sync failed err="state sync aborted" module=statesync

<img width="1141" alt="Screen Shot 2022-10-04 at 19 12 18" src="https://user-images.githubusercontent.com/27004732/193858554-b874c3b2-a00b-472f-a67d-62a9d898e90f.png">

**Comment by bjaanes** [comment]
After some investigation, it turns out that this was actually a bug in the SDK.

Issue has been created: https://github.com/cosmos/cosmos-sdk/issues/13766

Temporary workaround is to set the snapshot interval flags for the _syncing_ node.

**Comment by gjermundgaraba** [comment]
Solved in the SDK, should already be solved in 0.46.7, but we will at the very least be on 0.47 in any case, so closing this :)

**Comment by hdmiimdh** [comment]
Thank you very much @gjermundgaraba!
