### ISSUE TITLE
Simulation testing plasticcredit module

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#295]
Set up simulation testing for what we have + add it to CI

Reminders:
- [x] Update CODING_GUIDELINES
- [x] Add non-determinism and perhaps a short sim test to the regular test pipeline
- [x] Modules for import/export test

**Comment by bjaanes** [comment]
Closing in favor of separate issues

**Comment by gjermundgaraba** [comment]
There seems to not have been a separate issue :D Reopening!
