### ISSUE TITLE
Better release notes

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#317]
Not sure if we can generate them from a changelog document or something, but we need better release notes into our release process.
The current release process is:
1. Tag a release
2. The tag triggers this GHA workflow https://github.com/empowerchain/empowerchain/blob/main/.github/workflows/release.yml

**Comment by gjermundgaraba** [comment]
@ba1ciu @maheshKRex do any of you know how this works?
Look at the release notes here for instance: https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.7

Are they made manually or automatically?

**Comment by ba1ciu** [comment]
Looks like a manual process, this file is linked in the CI that creates the release:
https://github.com/cosmos/cosmos-sdk/blob/v0.46.7/RELEASE_NOTES.md

**Comment by gjermundgaraba** [comment]
wdyt, worth it?

**Comment by ba1ciu** [comment]
I'm up for creating manual release notes instead of making an automatic dump of PR messages or something like that. We'll have to follow everything we do with issues and epics for it to work well.

**Comment by gjermundgaraba** [comment]
Alright, let's do that then :+1:
