### ISSUE TITLE
Business rules limits

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#351]
We need to go over the different entities we have and look at where we need to set some limits to avoid abuse.

Potential examples include (but are not limited to):
- credit class abbreviations
- names for most entities

Some potential limitations to look for are:
- Specific business rules in terms of min/max-length
- Other rules

**Comment by gjermundgaraba** [comment]
@ba1ciu: assigning this to you. This task does not need to be the technical implementation of the rules, but trying to find any such rules that could be a good idea and probably ask around in the team for feedback and ideas.

**Comment by ba1ciu** [comment]
https://www.notion.so/empowerplastic/Blockchain-state-and-naming-validation-limits-4d6184b29b354887975502ab8308d71d

@gjermundgaraba If you approve, I'll close and create separate issues for implementation.

**Comment by gjermundgaraba** [comment]
Looks good to me! Feel free to close and create issues :+1:

**Comment by ba1ciu** [comment]
#448 
#449 
#450 
#451
