### ISSUE TITLE
Reject project

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#377]
New tx message to reject a project. 

- Only an admin from the issuer of the credit class referenced in the project is allowed to reject a project (See how this was done for Approve Project)
- It should not be possible to reject an already approved project
- It should not be possible to reject an already rejected project
- It should not be possible to issue credits for a project that has been rejected

Extra: Check and test that you can only approve projects that are in the NEW state (i.e. that you can approve a project that is already approved or rejected)

Tip: look at the code done in #354.

**Comment by maheshKRex** [comment]
@gjermundgaraba should we store a reason to reject from admin?

**Comment by gjermundgaraba** [comment]
Not for now.
