### ISSUE TITLE
Combine genesis test with invariant check for proof of existence

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#383]
Depends on #382

See how this was done in 382

**Comment by gjermundgaraba** [comment]
@ba1ciu anything in the poe module that would require invariant checking you think?

**Comment by ba1ciu** [comment]
The only thing coming to my mind is verifying hash format, but it's not breaking for the chain, so I suppose no invariants for PoE at this point?

**Comment by gjermundgaraba** [comment]
@ba1ciu this was done already?

**Comment by ba1ciu** [comment]
If done as no invariants needed then yes 😀

**Comment by gjermundgaraba** [comment]
Oh yeah, mixed this with the certificates module. Good, then I am closing this :)
