### ISSUE TITLE
Marketplace data model

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#418]
"Finalize" the marketplace data model.

```rust
/// Listing is the marketplace listing that a seller of a specific plastic credit denom creates.
/// Buyers can purchase as many credits as they like (up to a maximum of number_of_credits) from a listing.
/// This means that a single Listing can have many buyers
pub struct Listing {
    /// incremental, unique id
    pub id: u64,

    /// The address of the owner of this listing (and therefore also of the credits)
    pub owner: Addr,

    /// The credit denom that is for sale
    pub denom: String,

    /// The number of plastic credits that are for sale
    pub credits_available: Uint128,

    /// The asking price that the seller has set per credit. 
    pub price_per_credit: Coin,
}
```

**Comment by gjermundgaraba** [comment]
@ba1ciu I wonder if we need to have keep a record of each purchase that is made. I think we have to make it possible to have multiple buyers on a single listing (if someone has 1000 credits, we shouldn't force them to buy all I assume).

I have looked a bit into how other marketplaces work, and the typically don't keep the record on-chain, but we might want to do that for record-keeping and be able to display easily on the marketplace (in your account page). I assume an option is to use transactions and events and keep the records stored in an off-chain database. wdyt?

**Comment by ba1ciu** [comment]
Yes, this time I would go for just emitting events and indexing them off-chain. Storing transaction records in the state is a huge overkill, imo.
And multiple buyers, yes, definitely it should be possible to buy as many pcs as buyer wants (0<x<=number_of_credits). I guess we don't need a bidding system for now, unless there are going to be some super cool rare plastic credits. I assume that number_of_credits will update once someone buys the credits, but it might be useful to keep the original amount that was listed in the first place. Having "available x out of y" in the UI is a good way to highlight "hot" credits. Still, we'll have the original number indexed off-chain, so probably no need to add it to the state.

**Comment by gjermundgaraba** [comment]
@ba1ciu Been trying to think if there are any other things we might need on the model, or more importantly, if there are other entities needed, but I can't come up with anything else. 

We could certainly consider changing `number_of_credits` to `credits_for_sale`, `credits_left` or something like that. Seems like it would be a bit more clear that it is a number that would decrease as purchases are made.

**Comment by ba1ciu** [comment]
As for the model, nothing else comes to my mind too.
Yeah, we could change `number_of_credits` to `credits_left` or `credits_available` I'd say.
