### ISSUE TITLE
Create custom authz Authorization for MsgTransferCredits

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#426]
As per #423 we have decided to use authz with a custom Authorization message to enable the cosmwasm integration.

**Comment by amanPradhan05** [comment]
can I contribute?

**Comment by gjermundgaraba** [comment]
Hi @amanPradhan05, that is certainly possible. I have started this work, but if you want to do more on it I can help you going. Please contact me on Discord or Slack and we can take it from there.
