### ISSUE TITLE
Chain website is down

### ISSUE THREAD

**Issue by aljo242** [EmpowerPlastic/empowerchain#443]
https://empowerchain.io/ no longer works.

Perhaps also consider adding the following [action](https://github.com/gaurav-nelson/github-action-markdown-link-check).  The checks can be really noisy, but you can only run it against `main` once a week to make it more helpful.

**Comment by gjermundgaraba** [comment]
Yikes! Thanks for the heads-up! Some DNS issues that will hopefully be resolved soon. Will close this issue when it has been fixed.

It sounds like that action would be very useful, creating an issue for that.

**Comment by gjermundgaraba** [comment]
Seems to be sorted now. Thanks again, I really appreciate it :)
