### ISSUE TITLE
Add dead-link checker

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#444]
To make sure we don't have dead links in our markdown docs, let's add this action: https://github.com/gaurav-nelson/github-action-markdown-link-check

Also to make sure our own links are alive... Ref #443

**Comment by aljo242** [comment]
@gjermundgaraba can I take this task on?

**Comment by gjermundgaraba** [comment]
@aljo242 Take a look at the linked PR: #445 
I am not sure if there is much more needed or not
