### ISSUE TITLE
Credit Type creation needs additional fee

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#449]
# Background
We don't want a lot of credit types/classes that are not well though-out. So, to keep things a bit mellow we have decided to have a creation fee on new credit types that can be changed with governance. 

# Changes to be made
Credit Type creation is possible by an Issuer, who has to pay additional fee for creating new Credit Type.
⚠ Important note: In the code Credit Type is still called "Credit Class".

Two parts to this task:
1. Update the plasticcredit module parameters to have a credit class creation fee (denominated in sdk.Coin) that is controllable by governance. The default (genesis default) value should be 50 $MPWR.
2. Deduct the fee from the caller as part of the credit class creation and pay it to the community pool

**Comment by aljo242** [comment]
@gjermundgaraba can I pick up this issue?

**Comment by gjermundgaraba** [comment]
Yes @aljo242 go for it! Let me know if you have any questions :)

**Comment by gjermundgaraba** [comment]
Btw, the branch https://github.com/EmpowerPlastic/empowerchain/tree/449-credit-type-creation-needs-additional-fee has the params part implemented already I believe.

**Comment by aljo242** [comment]
@gjermundgaraba @ba1ciu 

Who is the fee paid to?

Issuer? Community pool? Burned?

Do we want to use a fee for updating credit classes as well?

**Comment by gjermundgaraba** [comment]
> Who is the fee paid to?
Ah, yeah. That should be the community pool. Updated the issue as well to clarify

> Do we want to use a fee for updating credit classes as well?
No, only for creating. Updated the issue with a bit more context to help make this clearer too :)
