### ISSUE TITLE
Module-wide description field validation

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#451]
We allow any utf-8 string of length up to 256 characters in description fields.

Implement the check in new utils/validation.go file in a similar manner to how it was done for name validation. For reference, see the name implementation here: #454

**Comment by aljo242** [comment]
@gjermundgaraba @ba1ciu starting this

**Comment by aljo242** [comment]
@ba1ciu @gjermundgaraba by "alpha numeric" do you mean literally only the characters 

```
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
```

I think it might be useful to allow for more characters than this such as punctuation, brackets, etc..

**Comment by gjermundgaraba** [comment]
@aljo242, yeah you are right, it should be utf-8 string.
