### ISSUE TITLE
Proof of Existence design

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#474]
**UI:** https://xd.adobe.com/view/64966487-a04d-46a8-a70b-514de322b6a6-31c5/grid/

**Comment by gjermundgaraba** [comment]
FYI @hasikam, converted this to a public issue in empowerchain repo

**Comment by hasikam** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4

**Comment by gjermundgaraba** [comment]
@hasikam This task is done, now?

**Comment by gjermundgaraba** [comment]
@hasikam Keeping this open because it tracks verify flow too which is still missing

**Comment by gjermundgaraba** [comment]
@hasikam status on the verify flow?

**Comment by gjermundgaraba** [comment]
@hasikam is there anything left on this now?
