### ISSUE TITLE
Automatic typescript types generated from empowerchain

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#475]
Some options to look into:
- "Raw" protobuf generation using buf and plugins
- Telescope: https://github.com/osmosis-labs/telescope
- Ignite's typescript client generation (https://docs.ignite.com/references/cli#ignite-generate-ts-client)

**Comment by ba1ciu** [comment]
Is this one left open to figure out types - frontend integration? @gjermundgaraba

**Comment by gjermundgaraba** [comment]
No real reason from my end. I suppose this is actually done, so will close it :)
