### ISSUE TITLE
Decide on css framework (or no framework)

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#476]
The proof of existence project is currently implemented with a combo of vanilla CSS (no pre or post processors) and Bootstrap as the framework.

Since bootstrap is a bit.. 2015, let's go for something that is a bit more modern and nice to use.

Very open to suggestions, but what we need to decide upon is:
- Pre and/or post processors
  - Examples: 
  - https://vanilla-extract.style/
  - SCSS
  - etc
- Framework
  - Examples:
  - Tailwind CSS
  - Bulma
  - etc

**Comment by ba1ciu** [comment]
Tailwind is cool! But it doesn't have pre-built components, so unless we're getting some serious designs in place, Bulma or Material are probably better.

_Sincerely,
Jakub, Frontend Expert_

**Comment by gjermundgaraba** [comment]
Hehe, this is true. But for the the proof of existence website we actually have the design pretty much good to go #474 

So perhaps Tailwind might even be a better fit if we are to follow that design (since it doesn't do any styling on its own)?

**Comment by PiranavanShanmugavadivelu** [comment]
I checked with tailwind CSS and Flowbite documentation. Both are looks good. We can easily switch to dark mode as well. There is a config file in the tailwind to set the theme and other style details. I tried out some Flowbite UI components look good. 

So I am choosing the tailwind CSS and the Flowbite UI components.

**Comment by PiranavanShanmugavadivelu** [comment]
@ba1ciu Great, Thank you
