### ISSUE TITLE
Clean up HTML, CSS

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#477]
Depends on #476

This task is simply to clean up the current code in the Proof of Existence frontend. 
clean up the HTML and CSS  and get the project ready for the rest of the implementation.

Including, **but not limited to**:
- Pull out components if needed
- Remove bootstrap and use whichever CSS solution decided in #476
- Put paddings and margins in variables
- Put colors and fonts in variables

**Comment by gjermundgaraba** [comment]
@PiranavanShanmugavadivelu no need to assign to me, even if it is in code review. It is more clear who has done the work if you just stay as the asignee on the issue. :)

**Comment by PiranavanShanmugavadivelu** [comment]
Sure, Thank you
