### ISSUE TITLE
Empowerchain typescript types integration into frontend

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#484]
We need to figure out the way we want to import the types generated in the telescope app (`frontend/ts-client`). Examples:

1. Use Lerna and import internal module.
2. Publish the module to npmjs as public or private package.

**Comment by ba1ciu** [comment]
@gjermundgaraba @PiranavanShanmugavadivelu FYI

**Comment by gjermundgaraba** [comment]
I was thinking the easiest is to just use lerna and import it directly. That way we don't have to deal with npm publishing until someone else needs it :)

**Comment by ba1ciu** [comment]
Agreed! I can try to wire it up or we can ask @PiranavanShanmugavadivelu for help here :)

**Comment by PiranavanShanmugavadivelu** [comment]
@ba1ciu Sure, I will look into this one.
