### ISSUE TITLE
Connect wallet

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#508]
Depends on #479

Need to support:
- Keplr: https://docs.keplr.app/api/cosmjs.html
- Leap: https://docs.leapwallet.io/cosmos/connect-to-leap/add-leap-to-a-new-dapp

To connect, get the `OfflineSigner` from the wallet and then use the `getSigningCosmosClient` function found in the empowerchain-ts-client.

Implement the connect wallet button:
![image](https://user-images.githubusercontent.com/1344105/220349171-8c0d2b96-4baf-47b0-be26-f7d7ee8e574f.png)

![image](https://user-images.githubusercontent.com/1344105/220377970-d533c917-3070-4ab4-9d3d-ed587d2c6d24.png)

![image](https://user-images.githubusercontent.com/1344105/220378078-b1770a35-a431-45a9-8aca-da8204ade166.png)

**Comment by ba1ciu** [comment]
@PiranavanShanmugavadivelu 
Here's the pseudocode how submitting the proof should look like:
```ts
const { createProof } =
  empowerchain.proofofexistence.MessageComposer.withTypeUrl;
const createProofMsg = createProof({
  creator: "put_user_address_here",
  hash: "put_calculated_hash_here",
});
const fee = {
  amount: [{ amount: "100000", denom: "umpwr" }],
  gas: "200000",
};
const response = await client.signAndBroadcast("sender_address", [createProofMsg], fee);
```
