### ISSUE TITLE
Update listing message

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#531]
### Update listing message:
```rust
UpdateListing {
  id: String,
  number_of_credits: Uin64,
  price_per_credit: Coin,
}
```
### Action response:
- action: update_listing
- listing_id: <ID>
- updated_by: <owner>
- number_of_credits: <updated_number_of_credits>
- price_per_credit: <updated_price_per_credit>

### Logic:
1. Fetch listing by ID.
2. Calculate if current number of credits in the listing is less or more than updated.
3. Transfer the balance from/to listing contract as per result of 2.
4. Update price per credit.

### Other changes:
1. Validation for listing creation, so only one listing for creator/denom pair can be present at a time.

**Comment by ba1ciu** [comment]
Added the spec.

For the separate field to track available credits, I think we should handle it with `number_of_credits`, because we don't exactly need a field in a listing that holds the initial amount of credits available? For marketplace view, we'll have an off-chain cache, which will take care of that. WDYT?

**Comment by gjermundgaraba** [comment]
> For the separate field to track available credits, I think we should handle it with `number_of_credits`, because we don't exactly need a field in a listing that holds the initial amount of credits available? For marketplace view, we'll have an off-chain cache, which will take care of that. WDYT @gjermundgaraba ?

Yeah, that is true. Agreed, lets just do it like that.

The spec looks good, I would perhaps rename the `listing_owner` attribute to `updated_by` or something. It should be the same right now, but if we add the ability for other to manage this we wouldn't need to change this.

**Comment by ba1ciu** [comment]
Also adding validation for listing creation, so only one listing for creator/denom can be created at once.
