### ISSUE TITLE
Set up CI/CD for proof of existence frontend

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#533]
We need to build, test (not sure we actually have any yet though) and deploy in CI/CD for proof of existence!

This one will probably require at least two Earthfiles, one in the root of the frontend folder, and another in the proof of existence folder. The main one (the one in the poe folder) would probably need to call into the root one to get lerna and everything set up. Maybe. I'm just thinking out loud at this point.

**Comment by gjermundgaraba** [comment]
@ba1ciu Something you want to take a crack at?

**Comment by ba1ciu** [comment]
Are we talking basic build, lint check, etc. + deploy or are we going to run automation tests also?
Yes, I think we're looking at a similar setup to what we use for Node backend - root Earthfile for lerna bootstrap and compile + other specific tasks in the poe's Earthfile.

I can take a crack at it, sure.
