### ISSUE TITLE
Restrict instantiation of the marketplace contract

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#546]
We have to figure out a way how to best restrict instantiation of the marketplace contract. Ideas:
1. Implement custom `instantiate()` entry point with a hardcoded address that is allowed to instantiate the contract.
2. Somehow use contract admin created at the contract upload.

**Comment by gjermundgaraba** [comment]
I forgot about this: https://github.com/CosmWasm/wasmd/blob/bc0e8179129a82dba4b9205c63e002c71cbb4edd/proto/cosmwasm/wasm/v1/tx.proto#L46

We can set this permission when we store the code. It can be set to governance, an address or even a list of addresses that are allowed to instantiate it.
