### ISSUE TITLE
Lighten e2e tests

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#559]
Review e2e tests and delete redundant ones because of existing unit/integration tests.

**Comment by maheshKRex** [comment]
Copying the nice summarisation of testing at different levels on chain, by @ba1ciu :
So we have:
1. Types and Messages tests (aka unit tests, types_test.go, msgs_test.go) - lowest level ones that should handle testing invalid message and object formats. Any higher level tests doing just that should be removed.
2. Genesis tests (genesis_test.go in module dir for testing object formats and genesis_test.go in keeper for testing init/export) - those are fine as they are and kinda separate from other tests.
3. Integration tests (msg_server_test.go and query_server_test.go) - middle level of tests (kinda controller level testing). Should use this for everything other than object/message validation. We can test interaction between different states in the same module thanks to PopulateWithSamples() . Good example of the test that should be done at this level.
4. Simulation tests - again, separate, should leave as it is.
5. Smoke tests - also separate. I'd vote for removing them entirely as they are doing the same as E2E tests, but wait for Gjermund with that.
6. E2E tests - highest level. Should be used when 1st and 3rd cannot be used.
So we should first test everything we can using 1, then other stuff using 3 and if there's still something to cover - 6.
