### ISSUE TITLE
Integrate cosmwasm client with EmpowerJS

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#608]
Background/Context
Ideally, we want a single library that will handle both cosmos and wasm transactions from typescript. That's why we should try to bundle up empowerjs and cw-client together.

How?
we should add wasm's proto to empowerjs and generate types for it
we should find a way to construct wasm messages and send them using EmpowerJS's stargate client ideally
our custom wasm messages that are generated in cw-client now should be moved to EmpowerJS and exported from there

**Comment by gjermundgaraba** [comment]
@ba1ciu please take a look at the changes I made in the branch - we need to discuss how to go ahead with this (aka. I need help :D)
