### ISSUE TITLE
Wallet errors should not go silent

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#640]
In PoE frontend, the app fails without showing any error message if something is wrong:

![image](https://user-images.githubusercontent.com/1344105/234022421-8ff2b8a3-0be8-4042-b78b-84c72a83f67d.png)

In this particular case the error is simple: the account doesn't exist yet.

So we need two things at least:
1. When something bad happens, show the error.
2. When this particular error happens tell the user that they account does not exist and that they need some $MPWR tokens

**Comment by gjermundgaraba** [comment]
If we don't have a notification system we should just add something

**Comment by gjermundgaraba** [comment]
@ba1ciu @PiranavanShanmugavadivelu do we have some kind of error notification/toast system we can just plug in and use here? Or does any UI libraries we are already using provide this?

**Comment by PiranavanShanmugavadivelu** [comment]
You can try this Flowbite toast - https://flowbite.com/docs/components/toast/
But If it is difficult try some npm libraries, Or shall I look at this one? It is easy for me to fix.

**Comment by ba1ciu** [comment]
I would go for daisyUI's toast. If we decided to go with daisy for the marketplace, it's a good idea to use it for PoE too.
