### ISSUE TITLE
Authz exec help menu example error

### ISSUE THREAD

**Issue by Relyte** [EmpowerPlastic/empowerchain#838]
**What**
The authz exec help menu has a typo in the example commands it provides on how to use it:

```
relyte@empowerchain:~$ empowerd tx authz exec -h
execute tx on behalf of granter account:
Example:
 $ "empowerd" tx authz exec tx.json --from grantee
 $ "empowerd" tx bank send <granter> <recipient> --from <granter> --chain-id <chain-id> --generate-only > tx.json && "empowerd" tx authz exec tx.json --from grantee
...
```

The `$ "empowerd" tx bank send <granter> <recipient> --from <granter> --chain-id <chain-id> --generate-only > tx.json` line contains an error where it's missing the send amount. If used as instructed the user is presented with an error saying that only 2 of 3 arguments were provided. 

**Fix**

The `$ "empowerd" tx bank send <granter> <recipient> --from <granter> --chain-id <chain-id> --generate-only > tx.json` line should be changed to `$ "empowerd" tx bank send <granter> <recipient> <amount> --from <granter> --chain-id <chain-id> --generate-only > tx.json`

**Comment by ba1ciu** [comment]
These examples are generated on the sdk level. You should submit this bug in cosmos-sdk repo.
