### ISSUE TITLE
Wallet Address Copy Issue

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#844]
issue - if you copy & paste your wallet only empower14l show only 
![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/d83909e1-dc82-46eb-8201-f1029a34f162)

**Comment by gjermundgaraba** [comment]
@PiranavanShanmugavadivelu let's do fours things here:
1. Change the address so it is a bit smaller and can show a bit more of the address
2. Allow the address to be a bit wider (again, so it can show a bit more of the address)
3. Show the last 4 characters of the address also (see picture below)
4. Add a little copy icon next to it (see picture below) and when the user clicks anywhere o the address or the copy icon, copy the address to the clipboard and show a toast with "Address copied to clipboard"

![image](https://github.com/EmpowerPlastic/empowerchain/assets/1344105/dd87e06d-5426-4bcc-a241-8b5227cd4232)
