### ISSUE TITLE
COLLECTOR ORGANISATION Filter Not Working

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#846]
I tried to use collector organisation filter but not working.

I select GreenEarth Waste Solutions in the filter but it doesn't show.

My expectation is that if you select **GreenEarth Waste Solutions** in the filter, only **GreenEarth Waste Solutions** will be displayed.

![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/9d0b6832-6cb8-4d18-abe2-9a855b8f25e2)

**Comment by gjermundgaraba** [comment]
I am not able to reproduce this anymore. Did we fix this recently @PiranavanShanmugavadivelu?

Also @cryptofanatic777, are you still seeing this issue? If so, can you share which browser?
