### ISSUE TITLE
Location Filter Not Working

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#847]
![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/a4d76917-a127-42c3-b6a9-a6327bd5aa39)

I tried to use Location Filter but not working.

I select **India** in the location filter but it doesn't show.

My expectation is that if you select **India** in the filter, only **India** location will be displayed.

**Comment by gjermundgaraba** [comment]
I am not able to reproduce this anymore. Did we fix this recently @PiranavanShanmugavadivelu?

Also @cryptofanatic777, are you still seeing this issue? If so, can you share which browser?

**Comment by cryptofanatic777** [comment]
Currently I'm using microsoft browser and I will try to other browser later.

**Comment by PiranavanShanmugavadivelu** [comment]
@gjermundgaraba  Recently @ba1ciu  fixed this from the back end side.
