### ISSUE TITLE
Market - Purchase Failed Bugs

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#848]
![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/3f445175-3364-4205-98bb-a642c501e5b1)

Market - Purchase Failed
1) I input 0 in the market 
2) Click Buy with MPWR 

Error Message Show  **Purchase Failed**

I suggest adding minimum amount if user want to purchase and disable the **Buy with MPWR** button if less than the minimum amount required.

**Comment by gjermundgaraba** [comment]
@PiranavanShanmugavadivelu let's disable the buy button if the user has chosen zero (or less).
