### ISSUE TITLE
Wallet - Unable to Disconnect

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#858]
![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/b6c57931-8fe2-40dc-b915-6123b7a6af28)
I tried to disconnect my wallet but unable to disconnect.

**Comment by gjermundgaraba** [comment]
We are adding a disconnect wallet button :rocket:

**Comment by PiranavanShanmugavadivelu** [comment]
Sure, On issue #840 covers this implementation
