### ISSUE TITLE
Node - Create Validator

### ISSUE THREAD

**Issue by dacyxs** [EmpowerPlastic/empowerchain#861]
I have running node in circulus testnet. After the sync is completed, I have tried to create validator. However, I could not do it first. 

The first code that I was trying;

empowerd tx staking create-validator \
--chain-id circulus-1 \
--commission-rate "0.1" \
 --commission-max-rate "0.2" \
--commission-max-change-rate "0.01"  \
--min-self-delegation "1000000"  \
--amount 1000000umpwr  \
--pubkey $(empowerd tendermint show-validator)  \
--moniker dacxys \
--from wallet \
--fees 5000umpwr

However, the code returns error which only mentions transaction is cancelled. There was no other info and I could note create validator for a while. 

Then, I tried as below;
empowerd tx staking create-validator --chain-id circulus-1 --commission-rate "0.1" --commission-max-rate "0.2" --commission-max-change-rate "0.01" --min-self-delegation "1000000" --amount 1000000umpwr --pubkey $(empowerd tendermint show-validator) --moniker dacxys --from wallet --fees 5000umpwr

I was able to complete successfully. I could not understand the reason but I believe there is a bug when trying to create validator.

![Screenshot 2023-06-09 235041](https://github.com/EmpowerPlastic/empowerchain/assets/106930902/228ac6bd-bc20-4317-823a-da1bb5662c7f)

**Comment by gjermundgaraba** [comment]
Are you able to reproduce this issue?
