### ISSUE TITLE
failed connect to keplr extension

### ISSUE THREAD

**Issue by xnode9** [EmpowerPlastic/empowerchain#865]
please help me 
![Screenshot_70](https://github.com/EmpowerPlastic/empowerchain/assets/96327197/640b772f-45cc-44a4-9899-9cbcceb73331)

**Comment by 0x0esd** [comment]
I think it's because this #859 PR
Commit hash [cc25050](https://github.com/EmpowerPlastic/empowerchain/pull/859/commits/cc250507ed3d66e7a6cdac12bad435fb238d2e2a) which remove the .env and change on workflows @gjermundgaraba

**Comment by gjermundgaraba** [comment]
This should be fixed by now, let me know if this can still be reproduced.
