### ISSUE TITLE
The "Create proof" button is blocked

### ISSUE THREAD

**Issue by toolfun** [EmpowerPlastic/empowerchain#870]
**Certify/Verify** documents app on https://testnet.proof-of-existence.com/

The `Create proof` button is blocked when the browser **ad blocker extension** is enabled. 
If you disable the extension and reload the page, the button is pressed and the action is performed. And vice versa. Tested with `uBlock Origin`, `AdBlocker Ultimate`.

**Comment by gjermundgaraba** [comment]
@PiranavanShanmugavadivelu see if you can reproduce this and figure out why this would be.

**Comment by PiranavanShanmugavadivelu** [comment]
I reproduced this using `uBlock Origin`. Trying to find out a way to fix this. Any idea on this @gjermundgaraba  @ba1ciu 
![image](https://github.com/EmpowerPlastic/empowerchain/assets/28488772/d7cefda2-3312-4ae3-9ce5-133f38e10436)

**Comment by gjermundgaraba** [comment]
Hmm, not sure. It is strange that an adblocker would block web assembly :thinking: We might need to have a backup sha256 function from javascript available when "window.empSha256" is not found.

When you're using the adblocker, can you see if the web assembly download is being blocked in the network tab?

**Comment by PiranavanShanmugavadivelu** [comment]
Ya, Exactly it is blocking the file `https://testnet.proof-of-existence.com/hash.wasm`

![image](https://github.com/EmpowerPlastic/empowerchain/assets/28488772/7306422a-8899-412e-8e88-4e8e64ebb74b)

**Comment by gjermundgaraba** [comment]
I assume this will block anything, but try to rename it from hash.wasm to empSha256.wasm and see if it still blocks it. If it does, we should implement an alternative when window.empSha256 is undefined.
