### ISSUE TITLE
Cannot read properties of undefined on View All Actions button

### ISSUE THREAD

**Issue by hdmiimdh** [EmpowerPlastic/empowerchain#878]
Steps to reproduce:

1. Go to https://testnet.empower.market/
2. Scroll down until till `View All Actions` button
3. Click on `View All Actions` button

Expected result: List of actions are displayed correctly or either message saying there're no actions.
Actual result: Infinite loader with console error `Cannot read properties of undefined (reading '0')`

<img width="1382" alt="Screenshot 2023-06-14 at 10 48 22" src="https://github.com/EmpowerPlastic/empowerchain/assets/27004732/392aae94-22fe-4119-9e89-f2e916bf7f37">

Attaching recording.
https://github.com/EmpowerPlastic/empowerchain/assets/27004732/77435a56-e132-4bca-8ec0-06c4459352a1

**Comment by PiranavanShanmugavadivelu** [comment]
@gjermundgaraba This issue was fixed recently from the Rollbar alert.
