### ISSUE TITLE
empowerd tx authz grant

### ISSUE THREAD

**Issue by AlexITProf** [EmpowerPlastic/empowerchain#881]
when creating Grant authorization to my secondary wallet, a zero balance error occurs

log:

alex@server:~$ empowerd keys list
- address: empower18ztk0s0dfxd664spnnya0wgd2v7846tkeh9rvr
  name: AlexIT
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AmZM5jfsA03wMDKPyojIl2QDcKnr1d3YCGEYh9AX4lNj"}'
  type: local
- address: empower1ayze7z7sn2sv8ql3aqwdl9r2aht23dqnw6n4j8
  name: wallet
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"Ar5v0AuAu4W8AcJ07UFePyd8lEJDHxIGwJTyUeXDWRG1"}'
  type: local

alex@server:~$ empowerd q bank balances empower18ztk0s0dfxd664spnnya0wgd2v7846tkeh9rvr
balances:
- amount: "23750"
  denom: umpwr
pagination:
  next_key: null
  total: "0"
alex@server:~$ empowerd q bank balances empower1ayze7z7sn2sv8ql3aqwdl9r2aht23dqnw6n4j8
balances:
- amount: "20100"
  denom: umpwr
pagination:
  next_key: null
  total: "0"
alex@server:~$ empowerd tx authz grant empower1ayze7z7sn2sv8ql3aqwdl9r2aht23dqnw6n4j8 send --from AlexIT --fees 200umpwr
Error: spend-limit should be greater than zero

**Comment by AlexITProf** [comment]
I understand that the full
if you specify the size of the grant, then the error of more arguments:

alex@server:~$ empowerd tx authz grant empower1ayze7z7sn2sv8ql3aqwdl9r2aht23dqnw6n4j8 send 200umpwr --from AlexIT --fees 200umpwr
Error: accepts 2 arg(s), received 3

I completed the task grand/revoke using the authorization_type=delegate
thank you)

**Comment by blntbytk** [comment]
i hava enough balances for both granter and grantee wallets but stil i had the message as out of gas at the explorer . https://empowerchain.exploreme.pro/transaction/8209A371B79A63270A3DAC3108BAA431E2BA4F2F3D37B28E170FB29F2364B527
empowerd tx authz grant empower1kupjfgt43uzuwc9v4lja4a4x3jl4wkqceh7n9k send --from blntbytk --chain-id circulus-1 --gas auto --gas-adjustment 1.5 --spend-limit 100umpwr --gas-prices 0.1umpwr

**Comment by toolfun** [comment]
@blntbytk It's more about --gas --fees flags. You may try this
`empowerd tx authz grant empower1kupjfgt43uzuwc9v4lja4a4x3jl4wkqceh7n9k send --spend-limit=100umpwr --chain-id circulus-1 --from blntbytk --fees 200umpwr`

**Comment by blntbytk** [comment]
Thx as you mentioned this is related to the gas , thx for your support

xAlex ***@***.***>, 18 Haz 2023 Paz, 18:38 tarihinde şunu
yazdı:
