### ISSUE TITLE
Transfer Credit Bugs (Add Invalid Wallet)

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#901]
![image](https://github.com/EmpowerPlastic/empowerchain/assets/135915618/043d4953-e562-464d-9a41-0fe974dc7c42)

https://github.com/EmpowerPlastic/empowerchain/assets/135915618/ebbeca9c-4ec5-4338-84b1-e3c5d039fac7

I tried to transfer credit to the invalid wallet address but the transaction still continued.
I suggest to adding invalid wallet popup message if user input invalid wallet and disable transfer if wallet address is invalid.

**Comment by 0x0esd** [comment]
so you mean it's only accept only `empower` prefix ?
