### ISSUE TITLE
Order buy history (My Transaction Not Recorded)

### ISSUE THREAD

**Issue by cryptofanatic777** [EmpowerPlastic/empowerchain#954]
https://github.com/EmpowerPlastic/empowerchain/assets/135915618/c9df7221-b19a-4e23-8c28-267d5566cd04

**Order buy history (My Transaction Not Recorded)**

Steps to Reproduce
1)Go to https://testnet.empower.market/auction
2)Select any ORGANISATION 
3)Click Buy with $MPWR
4)Accept the transaction 

Issue here my transaction not recorded in order buy history
My expectation is that you made a purchase and your transaction will automatically be listed in "Order buy history"

I suggest adding blockchain explorer link also.

**Comment by gjermundgaraba** [comment]
@ba1ciu is this information we are indexing already?

**Comment by ba1ciu** [comment]
We do! It's probably an issue with refreshing a view more than indexing. Moving to TODO.

**Comment by ba1ciu** [comment]
@PiranavanShanmugavadivelu There is refetch configured for listing details, but not for buy history. We should add it.

**Comment by ishaniranatunga** [comment]
@ba1ciu suppose i need to login to pay ? 

Could you give me a login to use for testing?

**Comment by ba1ciu** [comment]
@ishaniranatunga I guess we can close now? :)

**Comment by ishaniranatunga** [comment]
> ![2023-12-06_10-06-45](https://private-user-images.githubusercontent.com/66021919/288282435-12fa014f-abeb-468e-9ab6-b1e64c143c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDczMzgsIm5iZiI6MTcwMTk0NzAzOCwicGF0aCI6Ii82NjAyMTkxOS8yODgyODI0MzUtMTJmYTAxNGYtYWJlYi00NjhlLTlhYjYtYjFlNjRjMTQzYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDExMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MThlNGE2MGIwZGQ2MWY4NTZhMjJjYjU0MjhmMGVlZDVjOTBlMTRiZTU1OTNjNmZlOTJlNTM3MGFkMGI3NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pI74_u6ur3Serrb7QIq1wyFpN4Xho0YrHMsHilH5JL4)

MOved this issue to Plastic Credit V2 (Market Place): Login to Pay and Email options don't work #5856
